kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - kubeflow.org
    resources:
      - notebooks
    resourceNames:
      - {{ .Release.Name }}-workbench
  - verbs:
      - list
      - watch
    apiGroups:
      - kubeflow.org
    resources:
      - notebooks
