kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - list
    apiGroups:
      - datasciencepipelinesapplications.opendatahub.io
    resources:
      - datasciencepipelinesapplications
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
    apiGroups:
      - project.openshift.io
    resources:
      - projects
  - verbs:
      - get
      - patch
    apiGroups:
      - kubeflow.org
    resources:
      - notebooks
    resourceNames:
      - {{ .Release.Name }}-workbench
  - verbs:
      - list
    apiGroups:
      - kubeflow.org
    resources:
      - notebooks
  - verbs:
      - list
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
    apiGroups:
      - route.openshift.io
    resources:
      - routes
