{{ $namespace := .Release.Namespace }}
{{- range $group, $users := .Values.groups }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $group }}
  namespace: {{ $namespace }}
rules:
  - verbs:
      - list
    apiGroups:
      - datasciencepipelinesapplications.opendatahub.io
    resources:
      - datasciencepipelinesapplications
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
    apiGroups:
      - project.openshift.io
    resources:
      - projects
  - verbs:
      - get
      - patch
    apiGroups:
      - kubeflow.org
    resources:
      - notebooks
    resourceNames:
      - {{ $group }}-workbench
  - verbs:
      - list
    apiGroups:
      - kubeflow.org
    resources:
      - notebooks
  - verbs:
      - list
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
    apiGroups:
      - route.openshift.io
    resources:
      - routes
{{- end }}

{{- range $user := .Values.users }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $user }}
  namespace: {{ $namespace }}
rules:
  - verbs:
      - list
    apiGroups:
      - datasciencepipelinesapplications.opendatahub.io
    resources:
      - datasciencepipelinesapplications
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
    apiGroups:
      - project.openshift.io
    resources:
      - projects
  - verbs:
      - get
      - patch
    apiGroups:
      - kubeflow.org
    resources:
      - notebooks
    resourceNames:
      - {{ $user }}-workbench
  - verbs:
      - list
    apiGroups:
      - kubeflow.org
    resources:
      - notebooks
  - verbs:
      - list
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
    apiGroups:
      - route.openshift.io
    resources:
      - routes
{{- end }}
