{{ if not (lookup "rbac.authorization.k8s.io/v1" "RoleBinding" (include "user" .) (printf "dashboard-permissions-%s" (include "user" .))) -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dashboard-permissions-{{ template "user" . }}
  namespace: {{ template "user" . }}
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/project-sharing: 'true'
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: {{ template "user" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
{{- end }}