kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/project-sharing: 'true'
subjects:
{{- range $user := .Values.users }}
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: {{ $user }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-edit-no-notebooks
  namespace: {{ .Release.Namespace }}
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/project-sharing: 'true'
subjects:
{{- range $user := .Values.users }}
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: {{ $user }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit-no-notebooks
